spring:
 datasource:
  url: jdbc:sqlserver://azureserverdemo1.database.windows.net:1433;database=azuredb;user=saurabhsaini@azureserverdemo1;password=Bigbang@2018;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   
   
   
server:
  port: 9191 
  
  
